services:
  - type: web
    name: fairlens-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_ORIGINS
        value: https://fairlens-web.onrender.com
      - key: GOOGLE_API_KEY
        sync: false

  - type: web
    name: fairlens-web
    env: static
    staticPublishPath: .
